queue_rules:
  - name: feature_queue
    conditions:
      # - '#check-pending=0'
      - '#check-success>=2'
      - check-success=check-subject
      - check-success=unittest (on, 0)
      - check-success~=unittest

pull_request_rules:

  - name: put into queue if approved
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - check-success=check-subject
      - check-success=unittest (on, 0)
    actions:
      queue:
        name: feature_queue

  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
