[package]
name = "openraft-sledstore"
description = "A sled based implementation of the `openraft::RaftLogStorage` and `openraft::RaftStateMachine` trait."
documentation = "https://docs.rs/openraft-sledstore"
readme = "README.md"

version       = { workspace = true }
edition       = { workspace = true }
authors       = { workspace = true }
categories    = { workspace = true }
homepage      = { workspace = true }
keywords      = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }

[dependencies]
openraft = { path= "../../openraft", version = "0.10.0", features=["serde", "type-alias"] }

sled = "0.34.7"
byteorder = "1.4.3"
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
tracing         = { workspace = true }

[dev-dependencies]
tempfile = { version = "3.4.0" }

[features]
bt = ["openraft/bt"]

[package.metadata.docs.rs]
all-features = true
