[package]
name = "tests-sim"
description = "openraft integration tests on the deterministic simulated runtime (rt-sim)"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
openraft-rt-sim = { path = "../rt-sim", features = ["sim-log"] }

[dev-dependencies]
openraft          = { path = "../openraft", features = ["type-alias"] }
openraft-legacy   = { path = "../legacy", features = ["serde"] }
openraft-memstore = { path = "../stores/memstore", features = ["rt-sim"] }

anyhow             = { version = "1.0.63" }
derive_more        = { version = "2.1.1", features = ["std", "from", "try_into", "display"] }
futures            = { version = "0.3" }
lazy_static        = { version = "1.4.0" }
maplit             = { version = "1.0.2" }
pretty_assertions  = { version = "1.0.0" }
rand               = { version = "0.10" }
test-harness       = { version = "0.3.0" }
tracing            = { version = "0.1.40" }
tracing-appender   = { version = "0.2.0" }
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }

[features]
bt = ["openraft/bt"]
