[package]
name = "log-rocks"
version = "0.1.0"
readme = "README.md"

edition = "2024"
authors = [
    "drdr xp <drdr.xp@gmail.com>",
]
categories = ["algorithms", "asynchronous", "data-structures"]
description = "An example RocksDB-backed log storage for `openraft`."
homepage = "https://github.com/databendlabs/openraft"
keywords = ["raft", "consensus"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/databendlabs/openraft"

[dependencies]
openraft = { path = "../../openraft", version = "0.10.0-alpha.33", features = ["serde", "type-alias"] }

byteorder  = { version = "1.4.3" }
rocksdb    = { version = "0.22.0" }
serde      = { version = "1.0.114" }
serde_json = { version = "1.0.57" }
tracing    = { version = "0.1.40" }

[features]
bt = ["openraft/bt"]

[package.metadata.docs.rs]
all-features = true
