# `tokio_unstable` enables tokio's `Builder::rng_seed`, which turmoil uses to
# make tokio's `thread_rng_n` deterministic.
# Cargo merges this array with rustflags from outer config files.
[build]
rustflags = ["--cfg", "tokio_unstable"]
